version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: drupal/core-composer-scaffold
    versions:
    - ">= 9.a, < 10"
  - dependency-name: drupal/core-vendor-hardening
    versions:
    - ">= 9.a, < 10"
  - dependency-name: drupal/google_analytics
    versions:
    - ">= 3.a, < 4"
  - dependency-name: drush/drush
    versions:
    - ">= 10.a, < 11"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 6.a, < 7"
  - dependency-name: drupal/simple_sitemap
    versions:
    - 3.9.0
  - dependency-name: bower-asset/lazysizes
    versions:
    - 5.3.0
  - dependency-name: drupal/config_rewrite
    versions:
    - 1.4.0
  - dependency-name: drupal/core-dev
    versions:
    - 8.9.13
  - dependency-name: drupal/core-recommended
    versions:
    - 8.9.13
  - dependency-name: drupal/core-composer-scaffold
    versions:
    - 8.9.13
  - dependency-name: drupal/core-vendor-hardening
    versions:
    - 8.9.13
